[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
